#!/usr/bin/env python3
"""Build the MIO0-compressed segment blobs the game decompresses at runtime.

Four segments are not read as linked data -- the game MIO0-decodes them from a
compressed blob bracketed by <name>SegmentRomStart/End symbols. On MIPS the
Makefile emits a tiny .s per segment that .incbins the .mio0 between those two
labels; this does the same through file-scope __asm__, since RXDK builds only
.c/.cpp.

Getting this wrong is not subtle: stubbing the RomStart symbols as empty arrays
made mio0decode read a garbage header and write far outside its output buffer.
"""
import io, os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import coff_section
import coff_reloc

MIO0 = os.path.abspath("tools/mio0.exe")
OUT  = "Platform/xbox/gen_seg"
# Build objects live in the Release configuration's outputDir (rxdk.project.json);
# out/ is the legacy flat layout. Override with RXDK_OBJ_DIR.
OBJDIR = os.environ.get("RXDK_OBJ_DIR") or ("out/Release" if os.path.isdir("out/Release") else "out")
BS   = chr(92)
os.makedirs(OUT, exist_ok=True)

# (object, symbol stem as it appears in the .s -- already carrying the leading
#  underscore that x86 also uses for C symbols)
# Base addresses are the -Ttext values the Makefile links each segment at.
# These objects carry relocations too (91, 74, 135 and 73 respectively), so
# they need the same treatment as the course data.
SEGMENTS = [
    (OBJDIR + "/startup_logo.obj",   "_startupLogoSegment",    0x06000000),
    (OBJDIR + "/ceremony_data.obj",  "_ceremonyDataSegment",   0x0B000000),
    (OBJDIR + "/common_data.obj",    "_common_texturesSegment", 0x0D000000),
    (OBJDIR + "/data_segment2.obj",  "_data_segment2Segment",  0x02000000),
]

RELOCATED, _UNRES = coff_reloc.build([(o, b) for o, _, b in SEGMENTS])

# Segments whose blob must be the ROM'S OWN bytes, not a re-pack of the
# compiled C arrays. The common_data C arrays hold VALUE-order u16s (they are
# byteswapped in place at boot for direct-symbol consumers), so packing them
# produces a byte-flipped segment -- which is exactly what scrambled the shell
# palettes: their draw DLs reload the TLUT from this segment copy. The ROM's
# MIO0 block is the raw BE stream every segment consumer expects.
ROM_TRUTH = {
    OBJDIR + "/common_data.obj": 0x132B50,
}
ROM_PATH = "baserom.us.z64"

def rom_mio0(off):
    import struct
    rom = io.open(ROM_PATH, "rb").read()
    d = rom[off:off + 0x40000]
    us, co, ro = struct.unpack(">III", d[4:16])
    n = 0; lb = 16; lp = 0x10; ct = 0; cp = co; rp = ro
    while n < us:
        if lb == 16:
            ct = struct.unpack(">H", d[lp:lp+2])[0]; lp += 2; lb = 0
        if ct & 0x8000: rp += 1; n += 1
        else:
            v = struct.unpack(">H", d[cp:cp+2])[0]; cp += 2; n += (v >> 12) + 3
        ct = (ct << 1) & 0xFFFF; lb += 1
    return d[:max(lp, cp, rp)]

for obj, stem, _base in SEGMENTS:
    if not os.path.exists(obj):
        print("  missing object:", obj); continue
    binp  = os.path.join(OUT, os.path.basename(obj).replace(".obj", ".bin"))
    mio0p = binp.replace(".bin", ".mio0")
    if obj in ROM_TRUTH:
        blob = rom_mio0(ROM_TRUTH[obj])
        io.open(mio0p, "wb").write(blob)
        raw = b"\0" * len(blob)   # only len(raw) is printed below
        print("  %s <- ROM verbatim @%s" % (mio0p, hex(ROM_TRUTH[obj])))
    else:
        raw = RELOCATED.get(obj)
        if not raw:
            print("  no .data in", obj); continue
        io.open(binp, "wb").write(raw)
        r = subprocess.run([MIO0, "-c", binp, mio0p], capture_output=True)
        if r.returncode != 0 or not os.path.exists(mio0p):
            print("  compress failed:", obj); continue

    ap = os.path.abspath(mio0p).replace(BS, "/")
    lines = [
        ".data",
        ".balign 4",
        ".global _%s" % (stem + "RomStart"),
        "_%sRomStart:" % stem,
        '.incbin "%s"' % ap,
        ".balign 16",
        ".global _%s" % (stem + "RomEnd"),
        "_%sRomEnd:" % stem,
    ]
    cp = os.path.join(OUT, os.path.basename(obj).replace(".obj", "_blob.c"))
    import hashlib
    blob_hash = hashlib.sha1(io.open(mio0p, "rb").read()).hexdigest()[:16]
    with io.open(cp, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/gen_segblobs.py from %s.\n"
                " * blob sha1:%s -- the hash makes this TU's text change with the\n"
                " * incbin'd file, busting the compiler cache (zig cc does not track\n"
                " * .incbin dependencies; a stale cached object once shipped an old\n"
                " * segment blob and kept the shell palettes scrambled).\n"
                " * The MIO0 blob the game decodes at runtime, between the segment's\n"
                " * RomStart and RomEnd symbols -- the same shape the Makefile's\n"
                " * %%/*.mio0.s rule produces on MIPS. */\n" % (obj, blob_hash))
        f.write("__asm__(\n")
        for l in lines:
            f.write(chr(32)*4 + chr(34) + l.replace(chr(34), BS + chr(34)) + BS + 'n' + chr(34) + chr(10))
        f.write(");\n")
    print("  %-28s %8d raw -> %7d mio0" % (stem, len(raw), os.path.getsize(mio0p)))
